package ImageGenerator;

import javafx.scene.image.Image;
import javafx.scene.paint.Color;

/**
 * ImageGenerator takes a text and creates an image from it by parsing the text.
 */
public interface ImageGenerator {

    /**
     * setImageSize lets you choose the width and height of the output image.
     * By default it's 255x255
     * @param width
     * @param height
     */
    void setImageSize(int width, int height);

    /**
     * select the color of pixel that are not gonna be written explicitly by the parser
     * By default it's pure white (255, 255, 255)
     * @param color
     */
    void setBackgroundColor(Color color);

    /**
     * runs the parser and generates the image
     */
    void generateImage();

    /**
     * returns output image
     * @return the image generated by the parser. If generateImage() hasn't been executed successfully this returns null
     */
    Image getOutput();

}
